WebApplication/Models/FeverCheck.cs
namespace WebApplication.Models
{
    public class FeverCheck
    {
        public static string WriteMessage()
        {
            return "Please enter your temperature: ";
        }

        public static string Check(int temp)
        {
            if (temp >= 38)
                return "You have a fever.";
            else if (temp <= 35)
                return "You have Hypothermia";
            else
                return "You don't have a fever.";
        }
    }
}

WebApplication/Models/GuessingGame.cs
using System;
namespace WebApplication.Models
{
    public class GuessingGame
    {
       public static string MessageToPlayer()
        {
            return "Please enter your guess between 1 and 100: ";
        }

        public static string GuessNumber(int guess, int rndNr)
        {
                if (guess > rndNr)
                {
                return "Your guess is too high";
                }
                else if (guess < rndNr)
                {
                return "Your guess is too low";
                }
                else

                return "You have guessed the right number!";
            
        }
    }
}

WebApplication/Controllers/DoctorController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class DoctorController : Controller
    {
        public IActionResult FeverCheck()
        {
            ViewBag.Message = Models.FeverCheck.WriteMessage();
            return View();
        }
        [HttpPost]
        public IActionResult FeverCheck(int temp)
        {
            ViewBag.Info = Models.FeverCheck.Check(temp);
            return View();
        }
    }
}

WebApplication/Controllers/GameController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication.Models;
using Microsoft.AspNetCore.Http;
using System;

namespace WebApplication.Controllers
{
    public class GameController : Controller
    {
        public IActionResult MessageToPlayer()
        {
            ViewBag.Message1 = Models.GuessingGame.MessageToPlayer();
            return View();
        }

        public void RandomNr()
        {
            int rndNr = new Random().Next(1, 100);
            HttpContext.Session.SetInt32("RandomNr", rndNr);
        }
        public IActionResult GuessingGame()
        {
            RandomNr();
            return View();
        }
        private void CheckGuessNr(int guess)
        {
            if (HttpContext.Session.GetInt32("RandomNr") != null)
            {
                int rndNr = (int)HttpContext.Session.GetInt32("RandomNr");
                string Result = Models.GuessingGame.GuessNumber(guess, rndNr);
                ViewBag.Message2 = Result;
            }
        }
        [HttpPost]
        public IActionResult GuessingGame(int guess)
        {
            CheckGuessNr(guess);
            return View();
        }
    }
}

WebApplication/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVC_uppgift.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Contact()
        {
            return View();
        }
        public IActionResult Projects()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }
    }
}

WebApplication/Views/Doctor/FeverCheck.cshtml
@{
    ViewData["Title"] = "FeverCheck";
}

@if (ViewBag.Message != null)
{
    <h3>@ViewBag.Message</h3>
}

@if (ViewBag.Info != null)
{
    <h3>@ViewBag.Info</h3>
}

<form asp-controller="Doctor" asp-action="FeverCheck" method="post">
<label>Temperature: </label>
<input type="number" step=any name="temp" />
<input type="submit" value="Submit" />
</form>

WebApplication/Views/Game/GuessingGame.cshtml
@{
    ViewData["Title"] = "GuessingGame";
}

@if(ViewBag.Message1 != null){
    <h3>@ViewBag.Message1</h3>
}


<form asp-controller="Game" asp-action="GuessingGame" method="post">
<label>Please enter your guess between 1 and 100 </label>
<input type="number" step=any name="guess" />
<input type="submit" value="Submit" />
</form>



@if(ViewBag.Message2 != null){
    <h3>@ViewBag.Message2</h3>
}

WebApplication/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

   <h1>About</h1>
   <p> I am a 21 years old guy who like everything about technology and IT.   </p>

WebApplication/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}

<h1>Contact</h1>
<p> Herbert J. Boyd
148 Radio Park Drive
Augusta, GA 30901 </p>

WebApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";

}

<h1>LOGO</h1>
<p>  </p>

WebApplication/Views/Home/Projects.cshtml
@{
    ViewData["Title"] = "Projects";
}

<h1>Projects</h1>
<p> <a href="https://github.com/faizhallak/Calculator"> Calculator made with C#</a> </p>

WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
</head>
<body>
    <header>
       <h1>LOGO</h1>
        <menu>
            <li>
                <a asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li>
                <a asp-controller="Home" asp-action="About">About</a>
            </li>
            <li>
                <a asp-controller="Home" asp-action="Contact">Contact</a>
            </li>
            <li>
                <a asp-controller="Home" asp-action="Projects">Projects</a>
            </li>
            <li>
                <a asp-controller="Doctor" asp-action="FeverCheck">FeverCheck</a>
            </li>
            <li>
                <a asp-controller="Game" asp-action="GuessingGame">GuessingGame</a>
            </li>
        </menu>
    </header>
    <main>
        @RenderBody()
    </main>
    <footer>
        @DateTime.Now.ToShortDateString(); Faiz
    </footer>
</body>
</html>